### ISSUE TITLE
Bug Report: Password Input Validation for Existing Passwords

### ISSUE THREAD

**Issue by rairohit17** [jinx-vi-0/passop#95] opened 2024-10-13 08:34 UTC
Description: When attempting to store an existing password, the input validation process enforces validation rules, even though the password has already been created. This causes issues because users are forced to modify their passwords unnecessarily, potentially leading to problems when integrating with other services or remembering their passwords. Input validation should only be enforced when creating a new password, not when storing an existing one.

Steps to reproduce
Create a password that does not meet the input validation requirements.
Attempt to store this password in the system.
Observe that the system rejects the password due to input validation, even though the password already exists and was valid at the time of creation.

Expected behavior
The application must accept already existing passwords without validating them 

[Screencast from 2024-10-13 13-50-46.webm](https://github.com/user-attachments/assets/f3295e37-4ddd-4bf7-8992-3fe21c90581e)

**Comment by rairohit17** [comment] 2024-10-13 08:36
I would like to contribute by resolving this issue. I believe I can modify the validation logic to ensure that it applies only when creating or updating passwords, while allowing existing passwords to be stored without triggering validation rules.could you  assign me this issue  @jinx-vi-0

**Comment by jindalpriyanshu101** [comment] 2024-10-25 10:38
@jinx-vi-0 can you please handle it.

**Comment by adarsh-site** [comment] 2024-10-29 01:26
Assigned @rairohit17

**Comment by jindalpriyanshu101** [comment] 2024-11-04 13:02
> Steps to reproduce
Create a password that does not meet the input validation requirements.
Attempt to store this password in the system.
Observe that the system rejects the password due to input validation, even though the password already exists and was valid at the time of creation.

Hey there @rairohit17, it happens because validation wasn't added in previous versions of PassOP. which is just fine, as password validation is implemented as a security measure.

I just gone through your steps of reproducing bugs and came to conclusion that its not a bug, Instead it justified that the validation logic is working as it intended to be. About the bug you described, old passwords are meant to be updated periodically according to the validation rule as a security measure. 

Upon this re-evaluation, i'm marking this issue as invalid since removal of validation logic will compromise security measures nothing else.

**Comment by jindalpriyanshu101** [comment] 2024-11-04 13:03
Won't fix

**Closed as not planned by jindalpriyanshu101** 2024-11-04 13:03 UTC
Labels: invalid
